"""
FinWise AI — PostgreSQL Ingestion Script
=========================================
Reads finwise_users_v2.json (generated by generate_finwise_data_v2.py)
and ingests all users + transactions into the FinWise PostgreSQL database.

Requirements:
    pip install psycopg2-binary

Usage:
    # Basic ingestion
    python ingest_finwise_data.py

    # Custom DB connection
    python ingest_finwise_data.py --host localhost --port 5432 --db finwise --user finwise --password finwise

    # Custom JSON file path
    python ingest_finwise_data.py --file finwise_users_v2.json

    # Dry run (no DB writes)
    python ingest_finwise_data.py --dry-run

    # Clear existing synthetic data before ingesting
    python ingest_finwise_data.py --clear
"""

import argparse
import json
import sys
import time
import uuid
from datetime import datetime, date
from decimal import Decimal
from pathlib import Path

try:
    import psycopg2
    from psycopg2.extras import execute_batch, RealDictCursor
except ImportError:
    print("ERROR: psycopg2 not installed. Run: pip install psycopg2-binary")
    sys.exit(1)

# ── Config ────────────────────────────────────────────────────────────────────

DEFAULT_DB = dict(
    host="localhost",
    port=5432,
    dbname="finwise",
    user="finwise",
    password="finwise",
)

JSON_FILE = "finwise_users_v2.json"
BATCH_SIZE = 500   # rows per execute_batch call

# ── DB Connection ─────────────────────────────────────────────────────────────

def get_connection(args) -> psycopg2.extensions.connection:
    params = dict(
        host=args.host,
        port=args.port,
        dbname=args.db,
        user=args.user,
        password=args.password,
    )
    try:
        conn = psycopg2.connect(**params)
        conn.autocommit = False
        return conn
    except psycopg2.OperationalError as e:
        print(f"\n[ERROR] Cannot connect to PostgreSQL: {e}")
        print(f"  Make sure your DB is running and the credentials are correct.")
        print(f"  If using Docker: docker compose up -d")
        sys.exit(1)

# ── Schema Check ──────────────────────────────────────────────────────────────

REQUIRED_TABLES = {"users", "bank_accounts", "transactions"}

def check_schema(conn):
    with conn.cursor() as cur:
        cur.execute("""
            SELECT table_name FROM information_schema.tables
            WHERE table_schema = 'public'
        """)
        existing = {row[0] for row in cur.fetchall()}
    missing = REQUIRED_TABLES - existing
    if missing:
        print(f"\n[ERROR] Missing tables: {missing}")
        print("  Run your Flyway migrations or apply V1__initial_schema.sql first.")
        print("  With Spring Boot running: ./mvnw spring-boot:run (Flyway runs automatically)")
        sys.exit(1)
    print(f"[✓] Schema OK — tables: {', '.join(sorted(REQUIRED_TABLES))}")

# ── Clear Synthetic Data ──────────────────────────────────────────────────────

def clear_synthetic_data(conn):
    """Delete all rows tagged as synthetic data (source = 'SYNTHETIC')."""
    with conn.cursor() as cur:
        # transactions first (FK constraint)
        cur.execute("""
            DELETE FROM transactions
            WHERE user_id IN (
                SELECT user_id FROM users WHERE data_source = 'SYNTHETIC'
            )
        """)
        txn_del = cur.rowcount

        cur.execute("""
            DELETE FROM bank_accounts
            WHERE user_id IN (
                SELECT user_id FROM users WHERE data_source = 'SYNTHETIC'
            )
        """)
        acc_del = cur.rowcount

        cur.execute("DELETE FROM users WHERE data_source = 'SYNTHETIC'")
        usr_del = cur.rowcount

    conn.commit()
    print(f"[✓] Cleared synthetic data — {usr_del} users, {acc_del} accounts, {txn_del} transactions")

# ── Load JSON ─────────────────────────────────────────────────────────────────

def load_json(path: str) -> dict:
    p = Path(path)
    if not p.exists():
        print(f"\n[ERROR] File not found: {path}")
        print("  Generate it first: python generate_finwise_data_v2.py --count 50 --clear --save-map")
        sys.exit(1)
    with open(p) as f:
        data = json.load(f)
    print(f"[✓] Loaded {path} — {data.get('total_users', '?')} users, generated {data.get('generated_at', '?')}")
    return data

# ── Ingest Users ──────────────────────────────────────────────────────────────

def ingest_users(conn, users_data: list[dict], dry_run: bool) -> dict[str, str]:
    """
    Insert users into the users table.
    Returns a mapping of {name_archetype_key -> user_id} for account linking.
    Each user in users_data has: user_id, name, archetype, transactions
    """
    user_rows = []
    for u in users_data:
        user_rows.append((
            u["user_id"],                          # user_id (UUID)
            u["email"],                            # email
            "$2a$10$syntheticHashPlaceholder000",  # password_hash (bcrypt placeholder)
            u["name"],                             # full_name
            u.get("risk_profile", "MODERATE"),     # risk_profile
            u.get("income_bracket", "UNKNOWN"),    # income_bracket
            False,                                 # plaid_connected
            "SYNTHETIC",                           # data_source flag
            datetime.utcnow(),                     # created_at
            datetime.utcnow(),                     # updated_at
        ))

    if dry_run:
        print(f"  [DRY RUN] Would insert {len(user_rows)} users")
        return {u["user_id"]: u["user_id"] for u in users_data}

    sql = """
        INSERT INTO users (
            user_id, email, password_hash, full_name,
            risk_profile, income_bracket, plaid_connected,
            data_source, created_at, updated_at
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (user_id) DO NOTHING
    """
    with conn.cursor() as cur:
        execute_batch(cur, sql, user_rows, page_size=BATCH_SIZE)
    conn.commit()
    print(f"[✓] Inserted {len(user_rows)} users")
    return {u["user_id"]: u["user_id"] for u in users_data}

# ── Ingest Bank Accounts ──────────────────────────────────────────────────────

def ingest_accounts(conn, users_data: list[dict], dry_run: bool) -> dict[str, str]:
    """
    Create one synthetic bank account per user.
    Returns {user_id -> account_id}.
    """
    account_rows = []
    uid_to_aid = {}

    for u in users_data:
        account_id = str(uuid.uuid4())
        uid_to_aid[u["user_id"]] = account_id

        # Determine account type from archetype
        archetype = u.get("archetype", "")
        if archetype in ("high_earner", "dual_income"):
            acct_type = "CHECKING"
            institution = "Chase Bank"
        elif archetype in ("retired_fixed",):
            acct_type = "CHECKING"
            institution = "Fidelity Bank"
        elif archetype in ("small_biz_owner", "freelancer"):
            acct_type = "CHECKING"
            institution = "Bank of America"
        else:
            acct_type = "CHECKING"
            institution = "Wells Fargo"

        # Compute balance from transactions
        balance = sum(
            Decimal(str(t["amount"])) * (1 if t["transaction_type"] == "CREDIT" else -1)
            for t in u.get("transactions", [])
        )

        account_rows.append((
            account_id,
            u["user_id"],
            institution,
            f"{u['name'].split()[0]}'s Checking",
            acct_type,
            "****" + str(hash(u["user_id"]))[-4:],  # fake mask
            float(max(balance, Decimal("0"))),        # current_balance
            float(max(balance, Decimal("0"))),        # available_balance
            "USD",
            datetime.utcnow(),
            datetime.utcnow(),
        ))

    if dry_run:
        print(f"  [DRY RUN] Would insert {len(account_rows)} bank accounts")
        return uid_to_aid

    sql = """
        INSERT INTO bank_accounts (
            account_id, user_id, institution_name, account_name,
            account_type, mask, current_balance, available_balance,
            currency, created_at, updated_at
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (account_id) DO NOTHING
    """
    with conn.cursor() as cur:
        execute_batch(cur, sql, account_rows, page_size=BATCH_SIZE)
    conn.commit()
    print(f"[✓] Inserted {len(account_rows)} bank accounts")
    return uid_to_aid

# ── Ingest Transactions ───────────────────────────────────────────────────────

def ingest_transactions(conn, users_data: list[dict], uid_to_aid: dict[str, str], dry_run: bool):
    """Batch insert all transactions for all users."""
    tx_rows = []
    total = 0

    for u in users_data:
        account_id = uid_to_aid[u["user_id"]]
        for t in u.get("transactions", []):
            tx_rows.append((
                t["transaction_id"],         # transaction_id
                u["user_id"],                # user_id
                account_id,                  # bank_account_id
                t["transaction_type"],       # transaction_type (CREDIT/DEBIT)
                t["date"],                   # post_date
                t["description"],            # description
                t.get("merchant_name", t["description"]),  # merchant_name
                t["category"],               # category
                t.get("subcategory", None),  # subcategory
                float(t["amount"]),          # amount
                t.get("payment_method", "ACH"),  # payment_method
                t["transaction_id"],         # reference_id
                json.dumps({"archetype": u.get("archetype"), "synthetic": True}),  # metadata
            ))
            total += 1

            # Flush in batches to avoid memory issues
            if len(tx_rows) >= 5000 and not dry_run:
                _flush_transactions(conn, tx_rows)
                tx_rows = []

    if dry_run:
        print(f"  [DRY RUN] Would insert {total:,} transactions")
        return

    if tx_rows:
        _flush_transactions(conn, tx_rows)

    print(f"[✓] Inserted {total:,} transactions")

def _flush_transactions(conn, rows: list):
    sql = """
        INSERT INTO transactions (
            transaction_id, user_id, bank_account_id,
            transaction_type, post_date, description, merchant_name,
            category, subcategory, amount, payment_method,
            reference_id, metadata
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (transaction_id) DO NOTHING
    """
    with conn.cursor() as cur:
        execute_batch(cur, sql, rows, page_size=BATCH_SIZE)
    conn.commit()

# ── Flatten Users From JSON ───────────────────────────────────────────────────

def flatten_users(data: dict) -> list[dict]:
    """
    The JSON has structure:
      { "archetypes": { "high_earner": [ {...user...}, ... ], ... } }
    
    Flatten to a single list with archetype injected per user.
    Also generate email since the JSON may not have it.
    """
    users = []
    seen_emails = set()
    for archetype, user_list in data.get("archetypes", {}).items():
        for u in user_list:
            # Generate a unique email if not present
            if "email" not in u:
                base = u["name"].lower().replace(" ", ".").replace("'", "")
                email = f"{base}.{u['user_id'][:4]}@finwise-synthetic.com"
            else:
                email = u["email"]

            # Deduplicate emails (should not happen but just in case)
            if email in seen_emails:
                email = f"{u['user_id']}@finwise-synthetic.com"
            seen_emails.add(email)

            # Determine income bracket from avg monthly income
            avg_mo = u.get("avg_monthly_income", 0)
            annual = avg_mo * 12
            if annual < 50_000:
                bracket = "UNDER_50K"
            elif annual < 100_000:
                bracket = "50K_100K"
            elif annual < 200_000:
                bracket = "100K_200K"
            else:
                bracket = "OVER_200K"

            users.append({
                "user_id": u["user_id"],
                "name": u["name"],
                "email": email,
                "archetype": archetype,
                "income_bracket": bracket,
                "risk_profile": _archetype_to_risk(archetype),
                "transactions": u.get("transactions", []),
                "tx_count": u.get("tx_count", 0),
                "avg_monthly_income": avg_mo,
            })
    return users

def _archetype_to_risk(archetype: str) -> str:
    mapping = {
        "high_earner":       "AGGRESSIVE",
        "dual_income":       "MODERATE",
        "freelancer":        "MODERATE",
        "gig_worker":        "CONSERVATIVE",
        "high_debt":         "CONSERVATIVE",
        "overspender":       "CONSERVATIVE",
        "paycheck_to_paycheck": "CONSERVATIVE",
        "recent_grad":       "MODERATE",
        "retired_fixed":     "CONSERVATIVE",
        "small_biz_owner":   "AGGRESSIVE",
    }
    return mapping.get(archetype, "MODERATE")

# ── Summary ───────────────────────────────────────────────────────────────────

def print_summary(conn):
    with conn.cursor(cursor_factory=RealDictCursor) as cur:
        cur.execute("SELECT COUNT(*) AS cnt FROM users WHERE data_source = 'SYNTHETIC'")
        users = cur.fetchone()["cnt"]

        cur.execute("""
            SELECT COUNT(*) AS cnt FROM bank_accounts
            WHERE user_id IN (SELECT user_id FROM users WHERE data_source = 'SYNTHETIC')
        """)
        accounts = cur.fetchone()["cnt"]

        cur.execute("""
            SELECT COUNT(*) AS cnt FROM transactions
            WHERE user_id IN (SELECT user_id FROM users WHERE data_source = 'SYNTHETIC')
        """)
        txns = cur.fetchone()["cnt"]

        cur.execute("""
            SELECT
                u.income_bracket,
                COUNT(DISTINCT u.user_id) AS users,
                COUNT(t.transaction_id) AS txns,
                ROUND(AVG(t.amount)::numeric, 2) AS avg_txn_amount
            FROM users u
            JOIN transactions t ON t.user_id = u.user_id
            WHERE u.data_source = 'SYNTHETIC'
            GROUP BY u.income_bracket
            ORDER BY users DESC
        """)
        brackets = cur.fetchall()

    print(f"\n{'='*60}")
    print(f"  FINWISE DB INGESTION SUMMARY")
    print(f"{'='*60}")
    print(f"  Synthetic users:        {users:,}")
    print(f"  Bank accounts:          {accounts:,}")
    print(f"  Total transactions:     {txns:,}")
    print(f"  Avg txns per user:      {txns // max(users, 1):,}")
    print()
    print(f"  {'Income Bracket':<22} {'Users':>6} {'Txns':>8} {'Avg Txn $':>10}")
    print(f"  {'-'*22} {'-'*6} {'-'*8} {'-'*10}")
    for row in brackets:
        print(f"  {row['income_bracket']:<22} {row['users']:>6,} {row['txns']:>8,} {row['avg_txn_amount']:>10}")
    print(f"{'='*60}\n")

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="FinWise PostgreSQL Ingestion Script")
    parser.add_argument("--file",     default=JSON_FILE,          help="Path to finwise_users_v2.json")
    parser.add_argument("--host",     default=DEFAULT_DB["host"],  help="DB host")
    parser.add_argument("--port",     default=DEFAULT_DB["port"],  type=int)
    parser.add_argument("--db",       default=DEFAULT_DB["dbname"])
    parser.add_argument("--user",     default=DEFAULT_DB["user"])
    parser.add_argument("--password", default=DEFAULT_DB["password"])
    parser.add_argument("--dry-run",  action="store_true",         help="Parse + validate without writing to DB")
    parser.add_argument("--clear",    action="store_true",         help="Delete existing synthetic data first")
    parser.add_argument("--summary",  action="store_true",         help="Print DB summary after ingestion")
    args = parser.parse_args()

    print("\nFinWise Synthetic Data Ingestion v1")
    print("=" * 40)

    # 1. Load JSON
    raw = load_json(args.file)

    # 2. Flatten users
    users = flatten_users(raw)
    total_txns = sum(u["tx_count"] for u in users)
    print(f"[✓] Parsed {len(users):,} users with {total_txns:,} transactions")

    if args.dry_run:
        print("\n[DRY RUN MODE — no DB writes]")
        for u in users[:3]:
            print(f"  Sample: {u['name']} ({u['archetype']}) — {u['tx_count']} txns, ${u['avg_monthly_income']:,.0f}/mo")
        print(f"  ... and {len(users) - 3} more")
        return

    # 3. Connect
    conn = get_connection(args)
    print(f"[✓] Connected to PostgreSQL at {args.host}:{args.port}/{args.db}")

    # 4. Schema check
    check_schema(conn)

    # 5. Clear if requested
    if args.clear:
        clear_synthetic_data(conn)

    # 6. Ingest
    start = time.time()
    print("\nIngesting...")

    ingest_users(conn, users, dry_run=False)
    uid_to_aid = ingest_accounts(conn, users, dry_run=False)
    ingest_transactions(conn, users, uid_to_aid, dry_run=False)

    elapsed = time.time() - start
    print(f"\n[✓] Ingestion complete in {elapsed:.1f}s")

    # 7. Summary
    if args.summary:
        print_summary(conn)

    conn.close()


if __name__ == "__main__":
    main()
